name: Netlify E2E
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploymentUrl:
        description: 'Deployment URL to test with:'
        required: true
      prNumber:
        description: 'Pull request number (optional):'
        required: false
      shouldUpdateBaseline:
        description: 'Should the baseline be updated to reflect updates to the UI?'
        required: false
        default: "false"
jobs:
  check_config:
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.should_run.outputs.proceed }}
      site_name: ${{ steps.should_run.outputs.site_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Preliminary checks
        id: should_run
        env:
          DEPLOYMENT_URL: ${{ github.event.inputs.deploymentUrl }}
          DEPLOYMENT_STATUS: ${{ github.event.deployment_status.state }}
          TARGET_URL: ${{ github.event.deployment_status.target_url }}
        run: |
          SITE_NAME=$(jq -r '.netlifySiteName // empty' ci.config.json)

          if [[ -n "$DEPLOYMENT_URL" || -n "$SITE_NAME" ]]; then
            echo "proceed=true" >> $GITHUB_OUTPUT
          else
            echo "proceed=false" >> $GITHUB_OUTPUT
          fi

          echo site_name="$SITE_NAME" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
  netlify-e2e:
    needs: check_config
    if: needs.check_config.outputs.proceed == 'true'
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - uses: ./.github/actions/setup-playwright
      - name: Waiting for 200 from the Netlify Preview
        if: ${{ !github.event.inputs.deploymentUrl }}
        uses: jakepartusch/wait-for-netlify-action@v1.4
        id: waitFor200
        with:
          site_name: ${{ needs.check_config.outputs.site_name }}
          max_timeout: 120 # 2 Minutes, depends on your build pipeline duration
      - name: Set Run with URL
        run: |
          echo "DEPLOYMENT_URL=${{ github.event.inputs.deploymentUrl || steps.waitFor200.outputs.url }}" >> $GITHUB_ENV
      - uses: ./.github/actions/run-playwright
        id: runPlaywright
        with:
          provider: 'netlify'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          prNumber: ${{ github.event.inputs.prNumber || github.event.pull_request.number }}
          provider-deployment-url: ${{ env.DEPLOYMENT_URL }}
          shouldUpdateBaseline: ${{ github.event.inputs.shouldUpdateBaseline }}
          actor: ${{ github.actor }}
